<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>DotVgn</PackageId>
    <Description>.NET client for VAG/VGN API.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotVgn.Analyzers\DotVgn.Analyzers.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
    <ProjectReference Include="..\DotVgn.Common\DotVgn.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotVgn.Tests.Client" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\DotVgn.Analyzers\bin\$(Configuration)\netstandard2.0\DotVgn.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>
</Project>
